### ISSUE TITLE
colab cpu inference

### ISSUE THREAD

**Issue by AK391** [ben-hayes/neural-waveshaping-synthesis#2]
great work, is it possible to do inference on cpu in colab?
https://colab.research.google.com/github/ben-hayes/neural-waveshaping-synthesis/blob/main/colab/NEWT_Timbre_Transfer.ipynb

**Comment by ben-hayes** [comment]
Hi @AK391  :)

Thanks for the question. Yes it's very possible, although it wasn't very clear how. So, I've added two new cells to the notebook.

The first allows you to switch between using GPU and CPU (I'd recommend still using a GPU runtime just to make the CREPE pitch extraction faster, although it will work if you don't). The second allows you to activate the FastNEWT optimisation so you can compare generation times with and without it.

I'll close this issue now, but do let me know how you get on.

Best,

Ben

**Comment by AK391** [comment]
@ben-hayes thanks just to clarify the Extract Audio Features step is not required for inference?

**Comment by AK391** [comment]
@ben-hayes i see not using the full model cuts down the extract audio features time to 13 seconds from 4 minutes for 15 second audio from youtube

**Comment by ben-hayes** [comment]
Hi @AK391, yep the full CREPE model will run slowly on CPU. 

This is why I recommend either using the smaller CREPE model for pitch extraction or running the notebook on a GPU runtime (even if you’re running the neural waveshaping model on CPU).

Beyond the notebook, there’s nothing specifically tying you to CREPE, so if you have a particular application in mind where pitch extraction is necessary you could look at other algorithms like YIN, pYIN, or even something like BACF if speed is critical.

**Comment by AK391** [comment]
@ben-hayes thanks, I am looking to port the demo to gradio hub https://gradio.app/hub so inference on cpu was ideal, also what license would this be under?

**Comment by ben-hayes** [comment]
Hi @AK391,

I've uploaded a license to the repository, and it should be permissive enough for you to make a gradio port. I'm curious to hear how you get on — keep me in the loop!

Best

Ben

**Comment by AK391** [comment]
@ben-hayes thanks i have the demo setup here https://github.com/AK391/neural-waveshaping-synthesis/blob/main/gradiodemo.py and should be up on gradio hub soon. One question on monophonic input audio, I noticed all the samples were of singing, is it possible to feed piano input, I tried this one and it came out very noisy https://youtu.be/M_Lsh_QkyqM

**Comment by ben-hayes** [comment]
Hi @AK391, this is great, thank you.

The issue with piano input is that it's polyphonic and our model is conditioned on monophonic control signals. The noisy output is probably down to CREPE (a monophonic pitch extractor) being unable to predict pitch from a polyphonic input and thus producing a pretty crazy F0 estimate.

If you really wanted to apply the model to a monophonic input, there are maybe some options. It's difficult to accurately extract F0 from polyphonic signals, but there are algorithms to do so — if you are able to do this then you could successively apply the neural waveshaping model to each "layer" of control signals before summing to achieve something like a polyphonic output. If you do give this a shot, I'd love to hear the result!
